В домашнем задании необходимо применить полученные знания в теории оптимизации и машинном обучении для реализации логистической регрессии.

Этапы работы:

1. Загрузите данные. Используйте датасет с ирисами. Его можно загрузить непосредственно из библиотеки Sklearn. В данных оставьте только 2 класса: Iris Versicolor, Iris Virginica.

In [ ]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [ ]:
x_float, y_float, float_coeffs = make_regression(n_samples = 50, n_features = 4, n_informative = 4, noise = 10, coef = True, random_state = 11)  # Для проверки работоспособности линейной регрессии

In [ ]:
iris = datasets.load_iris()

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [ ]:
iris_df['target'] = iris.target

In [ ]:
iris_df = iris_df[iris_df['target'] != 0]

In [ ]:
iris_df.loc[:, 'target'] = iris_df['target'].apply(lambda x: x - 1)

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


In [ ]:
# iris_df['target'] = iris_df['target'].astype('category')

In [ ]:
iris_df.head(150)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                 7.0               3.2                4.7               1.4   
51                 6.4               3.2                4.5               1.5   
52                 6.9               3.1                4.9               1.5   
53                 5.5               2.3                4.0               1.3   
54                 6.5               2.8                4.6               1.5   
55                 5.7               2.8                4.5               1.3   
56                 6.3               3.3                4.7               1.6   
57                 4.9               2.4                3.3               1.0   
58                 6.6               2.9                4.6               1.3   
59                 5.2               2.7                3.9               1.4   
60                 5.0               2.0                3.5               1.0   
61                 5.9               3.0                4.2               1.5   
62                 6.0               2.2                4.0               1.0   
63                 6.1               2.9                4.7               1.4   
64                 5.6               2.9                3.6               1.3   
65                 6.7               3.1                4.4               1.4   
66                 5.6               3.0                4.5               1.5   
67                 5.8               2.7                4.1               1.0   
68                 6.2               2.2                4.5               1.5   
69                 5.6               2.5                3.9               1.1   
70                 5.9               3.2                4.8               1.8   
71                 6.1               2.8                4.0               1.3   
72                 6.3               2.5                4.9               1.5   
73                 6.1               2.8                4.7               1.2   
74                 6.4               2.9                4.3               1.3   
75                 6.6               3.0                4.4               1.4   
76                 6.8               2.8                4.8               1.4   
77                 6.7               3.0                5.0               1.7   
78                 6.0               2.9                4.5               1.5   
79                 5.7               2.6                3.5               1.0   
80                 5.5               2.4                3.8               1.1   
81                 5.5               2.4                3.7               1.0   
82                 5.8               2.7                3.9               1.2   
83                 6.0               2.7                5.1               1.6   
84                 5.4               3.0                4.5               1.5   
85                 6.0               3.4                4.5               1.6   
86                 6.7               3.1                4.7               1.5   
87                 6.3               2.3                4.4               1.3   
88                 5.6               3.0                4.1               1.3   
89                 5.5               2.5                4.0               1.3   
90                 5.5               2.6                4.4               1.2   
91                 6.1               3.0                4.6               1.4   
92                 5.8               2.6                4.0               1.2   
93                 5.0               2.3                3.3               1.0   
94                 5.6               2.7                4.2               1.3   
95                 5.7               3.0                4.2               1.2   
96                 5.7               2.9                4.2               1.3   
97                 6.2               2.9                4.3               1.3   
98                 5.1              

2. Самостоятельно реализуйте логистическую регрессию, без использования метода LogisticRegression из библиотеки. Можете использовать библиотеки pandas, numpy, math для реализации. Оформите в виде функции. *Оформите в виде класса с методами.

In [ ]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 50 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  100 non-null    float64
 1   sepal width (cm)   100 non-null    float64
 2   petal length (cm)  100 non-null    float64
 3   petal width (cm)   100 non-null    float64
 4   target             100 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 4.7 KB


In [ ]:
X = iris_df.drop(['target'], axis=1)

In [ ]:
X_stck = np.column_stack([X, np.ones((len(X)))])

In [ ]:
weights = np.zeros(X_stck.shape[1])
weights

array([0., 0., 0., 0., 0.])

In [ ]:
y = iris_df['target']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

In [ ]:
type(X_train)

pandas.core.frame.DataFrame

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train.head()

105    1
138    1
76     0
92     0
119    1
Name: target, dtype: int64

Свой вариант линейной и логистической регрессии (конечно, в разборном занятии отлично был сделан класс логистической регрессии, мне очень понравилась структура, кластеризация (особенно как разные виды регрессии и их методы применяются в зависимости от выбранного типа при инициализации класса, отграниченность методов fit, predict), я до такой структуры не дошел, поэтому сохранил себе как образец). Мой вариант выглядит ущербно, но самое главное - я понял основной смысл логистической регрессии и хотел бы двигаться дальше )):

In [ ]:
class Log_Regression_self_made():
  """Самостоятельно написанный вариант логистической регрессии"""  

  from sklearn.preprocessing import StandardScaler 

  def fit_test_sample_linear(self, x:pd.core.frame.DataFrame, y:pd.core.series.Series, learning_rate = 0.1, epochs = 50, eps = 0.0001, n_iterations = 100):

    """Для линейной регрессии, если значения Y это числа с плавающей точкой"""
    
    def mserror_mat(x_mserror, W, y_mserror):
      y_pred = x_mserror @ W
      return np.sum((y_mserror - y_pred)**2) / len(y_pred)

    def gr_mserror_mat(x_gr_error, W, y_gr_error):
      y_pred = x_gr_error @ W
      return 2/len(x_gr_error) * (y_gr_error - y_pred) @ (-x_gr_error)
    
    x_stack = np.column_stack([x, np.ones((len(x)))])
    weights = np.zeros(x_stack.shape[1])

    next_weights = weights

    for i in range(n_iterations):
      cur_weights = next_weights

      next_weights = cur_weights - learning_rate * gr_mserror_mat(x_stack, cur_weights, y)
      print(f'Итерация: {i}')
      print(f'Текущая точка {cur_weights} | Следующая точка {next_weights}')
      print(f'MSE: {mserror_mat(x_stack, cur_weights, y)}')
      print('---------------------------------------------------')

      if(np.linalg.norm(cur_weights - next_weights, ord=2) <= eps):
        break
  def fit_test_sample_logistic_one_dimensional(self, x:pd.core.frame.DataFrame, y:pd.core.series.Series, learning_rate = 0.1, epochs = 50, eps = 0.0001, n_iterations = 100):

    def sigmoid(x_sigm):
      return 1/(1+np.exp(-x_sigm))

    def logloss(y_logloss, y_proba_logloss):
      logloss_1 = np.sum(np.log(y_proba_logloss[y_logloss == 1] + 1e-30))
      logloss_0 = np.sum(np.log(1-y_proba_logloss[y_logloss==0] + 1e-30))
      logloss_total = -(logloss_0 + logloss_1) / len(y_logloss)
      return logloss_total

    def gr_logloss(x_logloss, W, y_logloss):
      y_pred = sigmoid(x_logloss @ W)
      grad = x_logloss.T @ (y_pred - y_logloss)
      return grad

    

    scaler = self.StandardScaler()

    np.random.seed(9)
    x_stack = np.column_stack([x, np.ones((len(x)))])
    weights = np.random.randn(x_stack.shape[1])
    next_weights = weights

    for i in range(n_iterations):
      cur_weights = next_weights   

      next_weights = cur_weights - learning_rate * gr_logloss(x_stack, cur_weights, y)

      if(np.linalg.norm(cur_weights - next_weights) <= eps):
        break

      if i % 80 == 0:        
        print(f'Итерация: {i}')
        y_proba = sigmoid(x_stack @ next_weights)
        y_class = np.where(y_proba >= 0.5, 1, 0)
        accuracy = (y_class == y).sum() / len(y)
        print(f'Logloss: {logloss (y, y_proba)}')
        print(f'Accuracy: {accuracy}')
        print(f'Y_proba: {y_proba}')
        print(f'Y_class: {y_class}')
        print (f'Current weights: {cur_weights}')
        print(f'actual y: {y.to_list()}')
        # print(f'y-scaler: {scaler.fit(y)}')
        print('---------------------------------------------------')


In [ ]:
model_self_made = Log_Regression_self_made()

In [ ]:
model_self_made.fit_test_sample_linear(x_float, y_float)

Итерация: 0
Текущая точка [0. 0. 0. 0. 0.] | Следующая точка [11.76469989  8.02019663  7.1529662   3.12227706 -0.71246521]
MSE: 7901.284047919273
---------------------------------------------------
Итерация: 1
Текущая точка [11.76469989  8.02019663  7.1529662   3.12227706 -0.71246521] | Следующая точка [21.07996752 15.00192791 13.15169841  5.97919733 -1.2826889 ]
MSE: 5491.413352110748
---------------------------------------------------
Итерация: 2
Текущая точка [21.07996752 15.00192791 13.15169841  5.97919733 -1.2826889 ] | Следующая точка [28.48213061 21.0576616  18.18254548  8.55326802 -1.72604536]
MSE: 3846.369420368778
---------------------------------------------------
Итерация: 3
Текущая точка [28.48213061 21.0576616  18.18254548  8.55326802 -1.72604536] | Следующая точка [34.38479911 26.29452131 22.40202941 10.84471509 -2.06001325]
MSE: 2714.9929661406427
---------------------------------------------------
Итерация: 4
Текущая точка [34.38479911 26.29452131 22.40202941 10.844715

In [ ]:
float_coeffs

array([59.32158596, 58.74342238, 44.07539836, 25.03682142])

In [ ]:
model_self_made.fit_test_sample_logistic_one_dimensional(X_train, y_train, n_iterations = 300)

Итерация: 0
Logloss: 32.81183757516514
Accuracy: 0.525
Y_proba: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1.]
Y_class: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1]
Current weights: [ 1.10855471e-03 -2.89544069e-01 -1.11606630e+00 -1.28827567e-02
 -3.78361464e-01]
actual y: [1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1]
---------------------------------------------------
Итерация: 80
Logloss: 18.388248323740395
Accuracy: 0.5875
Y_proba: [1.00000000e+00 1.00000000e+00 1.00000000e+00 9.

Логистическая регрессия из коробки

In [ ]:
model_test = LogisticRegression()

In [ ]:
model_test.fit(X_train, y_train)

LogisticRegression()

In [ ]:
model_test.score(X_train, y_train)

0.975

In [ ]:
model_test.predict(X_test)

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [ ]:
y_test.to_list()

[1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0]

In [ ]:
model_test.score(X_test, y_test)

0.95

In [ ]:
model_test.coef_

array([[-0.35674468, -0.73750193,  2.83425127,  2.19287166]])

Класс логистической регрессии, предложенный учителем:

In [ ]:
import time

class Teacher_s_Logistic_Regression:
  def __init__(self, epoch = 1000, learning_rate = 0.01, learn_method = 'gd', stop_rate = 0.0001):
    self.epoch = epoch
    self.learn_method = learn_method
    self.learning_rate = learning_rate
    self.stop_rate = stop_rate
    self.learn_func = None
    self.cost_func = None
    
    self.weights = None
    self.epoch_passed = 0
    self.learn_time = 0

    if(self.learn_method == 'gd'):
      self.learn_func = self.learn_gd
    elif(self.learn_method == 'rmsprop'):
      self.learn_func = self.learn_rmsprop
    elif(self.learn_method == 'adam'):
      self.learn_func = self.learn_adam
    elif(self.learn_method == 'nadam'):
      self.learn_func = self.learn_nadam
    else:
      raise Exception('Unknown learning method: {}'.format(self.learn_method))
    
  """Начальное инициализирование весов"""

  def init_weights(self, X):
    return np.zeros((X.shape[1], 1))

  """Обучение модели"""

  def fit(self, X, Y):
    X = self.addones(X)
    Y = np.reshape(Y, (len(Y), 1))
    W = self.init_weights(X)

    self.epoch_passed = 0
    self.learn_time = 0

    start = time.perf_counter()
    self.learn_func(X, Y, W)
    self.learn_time = time.perf_counter() - start

  """Отношение кол-ва правильных ответов к общему количеству ответов модели"""

  def score (self, X, Y):
    predictions = self.predict(X)
    scores = []
    for idx, y_pred in enumerate(predictions):
      # заполняем True если предсказание верное, иначе False:
      scores.append(True if y_pred == Y[idx] else False)

    return scores.count(True) / len(scores)


  """Количество прошедших итераций обучения"""

  def n_iter(self):
    return self.epoch_passed


  """Время обучения """

  def time(self):
    return self.learn_time


  """Список вероятностей ответа на основании признаков"""
  def predict_proba(self, X):
    X = self.addones(X)
    return self.sigmoid_linear_regression(X, self.weights)


  """Ответ обученной модели на основании признаков"""

  def predict(self, X):
    probas = self.predict_proba(X)
    for idx, y in enumerate(probas):
      probas[idx] = 1 if y > 0.5 else 0

    return probas


  """Добавляет единичный вектор к вектору признаков"""
  
  def addones(self, X):
    return np.hstack((np.ones((X.shape[0], 1)), X))


  """Метод, реализующий градиентный спуск (GD)"""

  def learn_gd(self, X, Y, W):
    prev = self.cost_binary_cross_entropy(X, Y, W)
    for enum in range (self.epoch):
      self.epoch_passed = enum+1
      gradients = self.gradient(X, Y, W)
      W = W - self.learning_rate * gradients
      actual = self.cost_binary_cross_entropy(X, Y, W)
      diff = abs(prev - actual)
      if( diff <= self.stop_rate):
        break
      prev = actual
    self.weights = W
    return W

  # не совсем понял, для чего нужны два абсолютно одинаковых метода - learn_gd, learn_sgd
  def learn_sgd(self, X, Y, W):
    prev = self.cost_binary_cross_entropy(X, Y, W)
    for enum in range (self.epoch):
      self.epoch_passed = enum+1

      gradients = self.gradient(X, Y, W)
      W = W - self.learning_rate * gradients
      actual = self.cost_binary_cross_entropy(X, Y, W)
      diff = abs(prev - actual)
      if( diff <= self.stop_rate):
        break
      prev = actual
    self.weights = W
    return W


  """Улучшенный градиентный спуск на основе rmsprop"""

  def learn_rmsprop(self, X, Y, W):
    prev = self.cost_binary_cross_entropy(X, Y, W)
    lr = self.learning_rate
    cached_rmsprop = [0] * len(W)
    decay_rate = 0.9
    for enum in range(self.epoch):
      self.epoch_passed = enum+1

    gradients = self.gradient(X, Y, W)
    NEW_W = []
    for i, (w, grad) in enumerate(zip(W, gradients)):
      cached_rmsprop[i] = decay_rate * cached_rmsprop[i] + (1-decay_rate) * grad**2
      new_w = w - lr*grad/(np.sqrt(cached_rmsprop[i] + 1e-6))
      NEW_W.append(new_w)

      W = NEW_W
      actual = self.cost_binary_cross_entropy(X, Y, W)
      diff = abs(prev - actual)
      if(diff <= self.stop_rate):
        break
      prev = actual

    self.weights = W
    return W

  """Улучшенный градиентный спуск на основе adam"""

  def learn_adam(self, X, Y, W):
    prev = self.cost_binary_cross_entropy(X, Y, W)
    lr = self.learning_rate
    m = [0] * len(W)
    v = [0] * len(W)
    t = 1
    beta1 = 0.9
    beta2 = 0.999
    for enum in range (self.epoch):
      self.epoch_passed = enum+1

      gradients = self.gradient(X, Y, W)
      NEW_W = []
      for i, (w, grad) in enumerate(zip(W, gradients)):
        m[i] = beta1 * m[i] + (1-beta1) * grad
        v[i] = beta2 * v[i] + (1-beta2) * grad**2
        m_corrected = m[i] / (1-beta1**t)
        v_corrected = v[i] / (1-beta2**t)

        new_w = w - lr*m_corrected / (np.sqrt(v_corrected + 1e-8))

        NEW_W.append(new_w)

      t+=1
      W = NEW_W
      actual = self.cost_binary_cross_entropy(X, Y, W)
      diff = abs(prev - actual)
      if(diff <= self.stop_rate):
        break
      prev = actual

    self.weights = W
    return W

  """Улучшенный градиентный спуск на основе nadam"""

  def learn_nadam(self, X, Y, W):
    prev = self.cost_binary_cross_entropy(X, Y, W)
    lr = self.learning_rate
    m = [0] * len(W)
    v = [0] * len(W)
    t = 1
    beta1 = 0.9
    beta2 = 0.999
    for enum in range (self.epoch):
      self.epoch_passed = enum+1

      gradients = self.gradient(X, Y, W)
      NEW_W = []
      for i, (w, grad) in enumerate(zip(W, gradients)):
        m[i] = beta1 * m[i] + (1-beta1) * grad
        v[i] = beta2 * v[i] + (1-beta2) * grad**2
        m_corrected = m[i] / (1-beta1**t)
        v_corrected = v[i] / (1-beta2**t)

        new_w = w - (lr/(np.sqrt(v_corrected) + 1e-8) * (beta1 * m_corrected + (1-beta1) * grad / (1 - beta1**t)))

        NEW_W.append(new_w)

      t+=1
      W = NEW_W
      actual = self.cost_binary_cross_entropy(X, Y, W)
      diff = abs(prev - actual)
      if(diff <= self.stop_rate):
        break
      prev = actual

    self.weights = W
    return W


  """Функция бинарной кросс-энтропии (векторная версия)"""

  def cost_binary_cross_entropy(self, X, Y, W):
    m = X.shape[0]
    total_cost = -(1/m) * np.sum(
        Y * np.log(self.sigmoid_linear_regression(X, W)) + (1 - Y) * np.log(
            1 - self.sigmoid_linear_regression(X, W)
        )
    )
    return total_cost

  """Производная от функции бинарной кросс-энтропии (векторная версия)"""

  def gradient(self, X, Y, W):
    m = X.shape[0]
    return (1/m) * np.dot(X.T, self.sigmoid_linear_regression(X, W) - Y)


  """Главная функция логистической регрессии"""

  def sigmoid_linear_regression(self, X, W):
    return self.sigmoid(self.linear_regression(X, W))


  """Функция линейной регрессии"""

  def linear_regression(self, X, W):
    return np.dot(X, W)

  
  """Функция сигмоиды (логистическая функция)"""

  def sigmoid(self, H):
    return 1 / (1 + np.exp(-H))

In [ ]:
teachers_model = Teacher_s_Logistic_Regression()

In [ ]:
teachers_model.fit(X_train, y_train.to_list())

In [ ]:
teachers_model.predict(X_test)

array([[1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.]])

Выводы:

1) Данное ДЗ мне показалось достаточно сложным, тем не менее спасибо вам за него, т.к. оно позволило глубже понять внутреннюю работу, которая стоит за результатами, которые мы получаем, вводя данные в классы библиотеки scikit-learn. 

2) Хоть основные моменты функционирования библиотеки sklearn мне стали более понятны, я ощутил нехватку системного понимания ее работы, которая, думаю, уменьшится после прочтения нескольких книг по Data Science. Мне попалась книга Geron A. - Hands-on Machine Learning with Scikit-Learn, Keras, and TensorFlow. Читали ли вы данную книгу, и если да, что вы думаете о ней? (Также с марта у меня появится больше свободного времени в связи с уменьшением нагрузки по основной работе, что позволит мне уделять гораздо больше времени на учебу и наверстать отставание по программе.)

3) Работа линейной и логистической регрессии стала гораздо более понятна после просмотра разборного занятия. Я считаю с нашим уровнем знаний самостоятельно построить модели линейной и логистической регрессии было просто нереально.

4) Тем не менее, хочется думать, что в будущем нас будут ждать такие же сложные челленджи, которые позволят нам увидеть собственные границы и шагнуть за их пределы.