In [1]:
import numpy as np
import pandas as pd 
import sympy as sym

In [2]:
film_1 = np.array([0,0,0,0,1,0])
film_2 = np.array([0,1,0,1,0,0])
film_3 = np.array([0,0,1,1,1,0])
film_4 = np.array([1,0,0,1,0,1])

Задание 1 - угол между фильмами Ярость и 12 лет рабства

In [12]:
def angle_bw_vectors(vec1, vec2):
    dot_films_2_3 = vec1.dot(vec2)
    norm_films_2_3 = np.linalg.norm(vec1) * np.linalg.norm(vec2)

    return np.rad2deg(np.arccos(dot_films_2_3 / norm_films_2_3))

In [13]:
angle_2_3 = angle_bw_vectors(film_2, film_3)

print(angle_2_3)

65.90515744788931


Задание 2 - вычислить значение первой производной для функции

In [5]:
x = sym.Symbol('x')
diff_func = 3*x * (x**2 + x)**3

res = sym.diff(diff_func, x)

print(res)

res

3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3


3*x*(6*x + 3)*(x**2 + x)**2 + 3*(x**2 + x)**3

Задание 3 - объединить векторы фильмов в матрицу и умножить вектор [1,2,3,4]  на полученную матрицу

In [6]:
film_matrix = np.array([film_1, film_2, film_3, film_4])

twisted_matrix = film_matrix.T

In [7]:
vect = np.array([1,2,3,4])

dot_multiply = twisted_matrix.dot(vect)

norm_multiply = np.linalg.norm(film_matrix) * np.linalg.norm(vect)

ordinary_multiply = twisted_matrix * vect

scalar_multiply = np.matmul(twisted_matrix, vect)

In [8]:
print(dot_multiply)

[4 2 3 9 4 4]


In [9]:
print(norm_multiply)

16.431676725154983


In [10]:
print(ordinary_multiply)

[[0 0 0 4]
 [0 2 0 0]
 [0 0 3 0]
 [0 2 3 4]
 [1 0 3 0]
 [0 0 0 4]]


In [11]:
print(scalar_multiply)

[4 2 3 9 4 4]
