In [1]:
import numpy as np

Задание 1

Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы
Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [2]:
matrix = np.arange(1,10).reshape(3,3)

matrix_plus_eye = matrix + np.eye(3,3)

matrix_multiplied_by_vector = matrix_plus_eye * np.array([1,2,3])

matrix_transposed = matrix_plus_eye.T

matrix_reversed = np.linalg.inv(matrix_plus_eye)


print(matrix)

print(matrix_plus_eye)

print(matrix_multiplied_by_vector)

print(matrix_transposed)

print(matrix_reversed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
[[ 2.  4.  9.]
 [ 4. 12. 18.]
 [ 7. 16. 30.]]
[[ 2.  4.  7.]
 [ 2.  6.  8.]
 [ 3.  6. 10.]]
[[-6.00000000e+00 -2.00000000e+00  3.00000000e+00]
 [-1.00000000e+00  5.00000000e-01 -2.33146835e-16]
 [ 5.00000000e+00  1.00000000e+00 -2.00000000e+00]]


In [3]:
matrix_plus_eye@matrix_reversed

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

Найдите собственные значения и собственные вектора матрицы:


In [4]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [5]:
proper_values_plus_vector = np.linalg.eig(m)

proper_values_plus_vector

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

In [6]:
proper_vectors = proper_values_plus_vector[1].T

In [7]:
proper_vectors[0] / 0.4472136

array([-1.99999998,  0.99999999])

In [8]:
proper_vectors[1] / -0.70710678

array([1., 1.])

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [9]:
matr = np.array([1,1,3,4]).reshape(2,2)

matr

array([[1, 1],
       [3, 4]])

In [10]:
np.linalg.det(matr)

0.9999999999999998