In [1]:
import numpy as np

In [2]:
zero_matrix = np.zeros([3, 3])

zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
eye_matrix = np.eye(3,3)

eye_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
ones_matrix = np.ones([3,3])

ones_matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])